version: '3'
services:
    server:
        build: './packages/server'
        environment:
            - HWJS_PORT=4000
            - HWJS_MONGODB_HOST=localhost:27017
        network_mode: host
        depends_on:
            - db
    db:
        image: mongo
        volumes:
            - ./data:/data/db
        network_mode: host
# networks:
#     hwjs_network:
#         driver: bridge
